import { Article } from '@/types';

export const articles: Article[] = [
  {
    slug: 'notice-to-vacate-letter-template',
    title: 'Notice to Vacate Letter Template: What to Include (2026)',
    description: 'Get a clean notice to vacate letter template, a checklist of what to include, and a calm plan for timing your move-out.',
    content: '',
    author: 'RentingExplained Editorial Team',
    publishDate: '2026-01-04T10:00:00Z',
    lastModified: '2026-01-04T10:00:00Z',
    category: 'Legal Rights',
    tags: ['notice-to-vacate', 'move-out', 'tenant-rights', 'lease-termination', 'templates'],
    readingTime: 12,
    image: '/images/legal-rights/notice-to-vacate-letter-template/notice-to-vacate-keys.webp',
    imageAlt: 'Apartment keys on a table near a lease',
    imageCredit: 'Photo by Jakub Zerdzicki on Unsplash',
  },
  {
    slug: 'apartment-move-out-checklist',
    title: 'Apartment Move-Out Checklist: Photos, Cleaning, Utilities',
    description: 'A renter-first move-out checklist covering photos, cleaning, walkthroughs, and utilities so you protect your deposit.',
    content: '',
    author: 'RentingExplained Editorial Team',
    publishDate: '2026-01-04T10:00:00Z',
    lastModified: '2026-01-04T10:00:00Z',
    category: 'Legal Rights',
    tags: ['move-out', 'security-deposit', 'checklist', 'tenant-rights', 'moving'],
    readingTime: 12,
    image: '/images/legal-rights/apartment-move-out-checklist/move-out-boxes.webp',
    imageAlt: 'Moving boxes in an empty apartment living room',
    imageCredit: 'Photo by Faruk Tokluoglu on Unsplash',
  },
  {
    slug: 'security-deposit-return-timeline',
    title: 'Security Deposit Return Timeline: What to Expect (2026)',
    description: 'Learn how security deposit return timelines work, what affects delays, and how to follow up without drama.',
    content: '',
    author: 'RentingExplained Editorial Team',
    publishDate: '2026-01-04T10:00:00Z',
    lastModified: '2026-01-04T10:00:00Z',
    category: 'Legal Rights',
    tags: ['security-deposit', 'tenant-rights', 'move-out', 'deposit-return', 'templates'],
    readingTime: 12,
    image: '/images/legal-rights/security-deposit-return-timeline/security-deposit-mailbox.webp',
    imageAlt: 'Mailbox with an envelope and keys nearby',
    imageCredit: 'Photo by Valeria Nikitina on Unsplash',
  },
  {
    slug: 'how-much-rent-can-i-afford',
    title: 'How Much Rent Can I Afford? A Realistic Budget Guide (2026)',
    description: 'Learn how much rent you can realistically afford based on income, debt, and lifestyle without relying on rigid rules.',
    content: '',
    author: 'RentingExplained Editorial Team',
    publishDate: '2026-01-08T10:00:00Z',
    lastModified: '2026-01-08T10:00:00Z',
    category: 'Financial Planning',
    tags: ['rent-budget', 'affordability', 'financial-planning', 'budgeting', 'rent-costs'],
    readingTime: 12,
    image: '/images/financial-planning/how-much-rent-can-i-afford/how-much-rent-can-i-afford-hero.webp',
    imageAlt: 'Calculator and budget notes on a desk',
    imageCredit: 'Photo by Kelly Sikkema on Unsplash',
  },
  {
    slug: 'rental-scams-how-to-avoid',
    title: 'Rental Scams Explained: How to Spot Fake Listings and Stay Safe',
    description: 'Learn how rental scams work, warning signs to watch for, and simple steps to verify listings before sending money.',
    content: '',
    author: 'RentingExplained Editorial Team',
    publishDate: '2026-01-09T10:00:00Z',
    lastModified: '2026-01-09T10:00:00Z',
    category: 'Apartment Hunting',
    tags: ['rental-scams', 'apartment-hunting', 'safety', 'rental-listings', 'moving'],
    readingTime: 12,
    image: '/images/apartment-hunting/rental-scams-how-to-avoid/rental-scams-how-to-avoid-hero.webp',
    imageAlt: 'Person reviewing rental application documents',
    imageCredit: 'Photo by Hunters Race on Unsplash',
  },
  {
    slug: 'renting-with-bad-credit-options',
    title: 'Renting With Bad Credit: Options, Cosigners, and What Helps',
    description: 'Learn how renters with bad credit get approved, when cosigners help, and how to strengthen an application.',
    content: '',
    author: 'RentingExplained Editorial Team',
    publishDate: '2026-01-10T10:00:00Z',
    lastModified: '2026-01-10T10:00:00Z',
    category: 'Apartment Hunting',
    tags: ['bad-credit', 'rental-application', 'tenant-screening', 'apartment-hunting', 'cosigner'],
    readingTime: 12,
    image: '/images/apartment-hunting/renting-with-bad-credit-options/renting-with-bad-credit-options-hero.webp',
    imageAlt: 'Person reviewing credit paperwork at a desk',
    imageCredit: 'Photo by Scott Graham on Unsplash',
  },
  {
    slug: 'apartment-approval-requirements',
    title: 'Apartment Approval Requirements: What Landlords Look For (2026)',
    description: 'Learn what landlords look for in an apartment application, from credit and income to rental history and complete paperwork.',
    content: '',
    author: 'RentingExplained Editorial Team',
    publishDate: '2026-01-11T10:00:00Z',
    lastModified: '2026-01-11T10:00:00Z',
    category: 'Rental Approval & Eligibility',
    tags: ['rental-approval', 'tenant-screening', 'application', 'income', 'rental-history'],
    readingTime: 12,
    image: '/images/rental-approval/apartment-approval-requirements/apartment-approval-requirements-hero.webp',
    imageAlt: 'Person reviewing rental application documents',
    imageCredit: 'Photo by Hunters Race on Unsplash',
  },
  {
    slug: 'proof-of-income-for-apartments',
    title: 'Proof of Income for Apartments: What Counts and How to Prepare',
    description: 'Learn what counts as proof of income for apartments, which documents landlords accept, and how to organize them.',
    content: '',
    author: 'RentingExplained Editorial Team',
    publishDate: '2026-01-12T10:00:00Z',
    lastModified: '2026-01-12T10:00:00Z',
    category: 'Rental Approval & Eligibility',
    tags: ['proof-of-income', 'rental-application', 'tenant-screening', 'income-docs', 'approval'],
    readingTime: 12,
    image: '/images/rental-approval/proof-of-income-for-apartments/proof-of-income-for-apartments-hero.webp',
    imageAlt: 'Person reviewing income paperwork at a desk',
    imageCredit: 'Photo by Scott Graham on Unsplash',
  },
  {
    slug: 'minimum-income-to-rent-apartment',
    title: 'Minimum Income to Rent an Apartment: 3x Rent Rule Explained',
    description: 'Learn how the 3x rent rule works, how to calculate it, and when landlords make exceptions.',
    content: '',
    author: 'RentingExplained Editorial Team',
    publishDate: '2026-01-13T10:00:00Z',
    lastModified: '2026-01-13T10:00:00Z',
    category: 'Rental Approval & Eligibility',
    tags: ['income-requirements', '3x-rent-rule', 'rent-budget', 'approval', 'financial-planning'],
    readingTime: 12,
    image: '/images/rental-approval/minimum-income-to-rent-apartment/minimum-income-to-rent-apartment-hero.webp',
    imageAlt: 'Calculator and budget notes on a desk',
    imageCredit: 'Photo by Kelly Sikkema on Unsplash',
  },
  {
    slug: 'rent-increase-renewal-guide',
    title: 'Rent Increase Notice: How to Respond at Renewal (2025)',
    description: 'A renter-first guide to renewal rent increases with clear options, scripts, and budget steps.',
    content: '',
    author: 'RentingExplained Editorial Team',
    publishDate: '2026-01-07T10:00:00Z',
    lastModified: '2026-01-07T10:00:00Z',
    category: 'Costs',
    tags: ['rent-increase', 'renewal', 'budgeting', 'costs', 'rent-negotiation'],
    readingTime: 11,
    image: '/images/costs/rent-increase-renewal-guide/rent-increase-renewal-guide-hero.webp',
    imageAlt: 'Person reviewing paperwork and a calculator at a desk',
    imageCredit: 'Photo by Scott Graham on Unsplash',
  },
  {
    slug: 'renters-insurance-cost-2025',
    title: 'Renters Insurance Cost in 2025: Coverage Basics and Ways to Save',
    description: 'A renter-first guide to renters insurance costs, coverage choices, and ways to lower your premium.',
    content: '',
    author: 'RentingExplained Editorial Team',
    publishDate: '2026-01-06T10:00:00Z',
    lastModified: '2026-01-06T10:00:00Z',
    category: 'Costs',
    tags: ['renters-insurance', 'insurance', 'budgeting', 'costs', 'protection'],
    readingTime: 11,
    image: '/images/costs/renters-insurance-cost-2025/renters-insurance-cost-2025-hero.webp',
    imageAlt: 'Person reviewing insurance documents at a desk',
    imageCredit: 'Photo by Brooke Cagle on Unsplash',
  },
  {
    slug: 'apartment-utility-costs',
    title: 'Apartment Utility Costs: How to Lower Monthly Bills Without Breaking Your Lease',
    description: 'A renter-first guide to understanding utility bills, quick savings, and a simple audit checklist.',
    content: '',
    author: 'RentingExplained Editorial Team',
    publishDate: '2026-01-05T10:00:00Z',
    lastModified: '2026-01-05T10:00:00Z',
    category: 'Costs',
    tags: ['utilities', 'budgeting', 'costs', 'saving-money', 'apartment-life'],
    readingTime: 11,
    image: '/images/costs/apartment-utility-costs/apartment-utility-costs-hero.webp',
    imageAlt: 'Desk with notes and a calculator for utility budgeting',
    imageCredit: 'Photo by Patrick Perkins on Unsplash',
  },
  {
    slug: 'apartment-move-in-costs',
    title: 'Apartment Move-In Costs: Checklist and Budget Guide (2025)',
    description: 'A renter-first breakdown of move-in costs, fees, and a checklist to budget before you get the keys.',
    content: '',
    author: 'RentingExplained Editorial Team',
    publishDate: '2026-01-04T10:00:00Z',
    lastModified: '2026-01-04T10:00:00Z',
    category: 'Costs',
    tags: ['move-in-costs', 'budgeting', 'apartment-hunting', 'rental-fees', 'first-apartment'],
    readingTime: 11,
    image: '/images/costs/apartment-move-in-costs/apartment-move-in-costs-hero.webp',
    imageAlt: 'Moving boxes in a bright apartment living room',
    imageCredit: 'Photo by Christian Mackie on Unsplash',
  },
  {
    slug: 'rental-application-checklist',
    title: 'Rental Application Checklist: Documents, Fees, and Timing',
    description: 'A calm checklist of rental application documents, fees, and timing so you can apply fast and avoid delays.',
    content: '',
    author: 'RentingExplained Editorial Team',
    publishDate: '2025-02-05T10:00:00Z',
    lastModified: '2025-02-05T10:00:00Z',
    category: 'Apartment Hunting',
    tags: ['apartment-hunting', 'rental-application', 'background-check', 'first-apartment', 'moving'],
    readingTime: 12,
    image: '/images/apartment-hunting/rental-application-checklist/rental-application-checklist-hero.webp',
    imageAlt: 'Person reviewing rental application documents',
    imageCredit: 'Photo by Hunters Race on Unsplash',
  },
  {
    slug: 'apartment-tour-checklist-questions-red-flags',
    title: 'Apartment Tour Checklist: Questions to Ask and Red Flags to Spot',
    description: 'A practical tour checklist with questions to ask, red flags to notice, and notes to take before you apply.',
    content: '',
    author: 'RentingExplained Editorial Team',
    publishDate: '2025-02-04T10:00:00Z',
    lastModified: '2025-02-04T10:00:00Z',
    category: 'Apartment Hunting',
    tags: ['apartment-hunting', 'apartment-tour', 'rental-inspection', 'moving', 'first-apartment'],
    readingTime: 12,
    image: '/images/apartment-hunting/apartment-tour-checklist-questions-red-flags/apartment-tour-checklist-questions-red-flags-hero.webp',
    imageAlt: 'Bright apartment living room during a tour',
    imageCredit: 'Photo by Austin Distel on Unsplash',
  },
  {
    slug: 'tenant-screening-credit-checks-for-renters',
    title: 'Tenant Screening and Credit Checks for Renters: What Landlords Look For',
    description: 'A clear guide to tenant screening, credit checks, and how landlords evaluate applications.',
    content: '',
    author: 'RentingExplained Editorial Team',
    publishDate: '2025-02-03T10:00:00Z',
    lastModified: '2025-02-03T10:00:00Z',
    category: 'Apartment Hunting',
    tags: ['apartment-hunting', 'tenant-screening', 'credit-check', 'rental-application', 'first-apartment'],
    readingTime: 12,
    image: '/images/apartment-hunting/tenant-screening-credit-checks-for-renters/tenant-screening-credit-checks-for-renters-hero.webp',
    imageAlt: 'Person reviewing credit and screening paperwork',
    imageCredit: 'Photo by Scott Graham on Unsplash',
  },
  {
    slug: 'how-to-negotiate-rent-guide',
    title: 'How to Negotiate Rent in 2025: Practical Scripts and Timing Tips',
    description: 'A renter-first guide to asking for lower rent or better terms with simple scripts and smart timing.',
    content: '',
    author: 'RentingExplained Editorial Team',
    publishDate: '2025-01-27T10:00:00Z',
    lastModified: '2025-01-27T10:00:00Z',
    category: 'Money Saving',
    tags: ['rent-negotiation', 'saving-money', 'lease-negotiation', 'rent-increase', 'apartment-hunting'],
    readingTime: 17,
    image: '/images/money-saving/how-to-negotiate-rent-guide/how-to-negotiate-rent-guide-hero.webp',
    imageAlt: 'Person reviewing budget and negotiating rent terms',
    imageCredit: 'Photo by Kelly Sikkema on Unsplash',
  },
  {
    slug: 'first-apartment-checklist-budget-guide',
    title: 'First Apartment Budget Guide: What to Buy and What to Skip',
    description: 'A room-by-room budget guide for first-time renters with realistic tiers and a simple buying timeline.',
    content: '',
    author: 'RentingExplained Editorial Team',
    publishDate: '2025-01-26T10:00:00Z',
    lastModified: '2025-01-26T10:00:00Z',
    category: 'Apartment Hunting',
    tags: ['first-apartment', 'first-time-renter', 'apartment-checklist', 'budgeting', 'moving'],
    readingTime: 18,
    image: '/images/apartment-hunting/first-apartment-checklist-budget-guide/first-apartment-checklist-budget-guide-hero.webp',
    imageAlt: 'Moving boxes in a new apartment for a first apartment checklist',
    imageCredit: 'Photo by Ketut Subiyanto on Unsplash',
  },
  {
    slug: 'breaking-a-lease-without-penalty-2025',
    title: 'Breaking a Lease Without Penalty: Legal Options and Safer Steps (2025)',
    description: 'A renter-first guide to legal lease exits, documentation tips, and negotiating a clean release.',
    content: '',
    author: 'RentingExplained Editorial Team',
    publishDate: '2025-01-25T10:00:00Z',
    lastModified: '2025-01-25T10:00:00Z',
    category: 'Legal Rights',
    tags: ['lease-termination', 'tenant-rights', 'legal', 'lease-break', 'moving'],
    readingTime: 16,
    image: '/images/legal-rights/breaking-a-lease-without-penalty-2025/breaking-a-lease-without-penalty-2025-hero.webp',
    imageAlt: 'Lease document and pen representing breaking a lease without penalty',
    imageCredit: 'Photo by Tingey Injury Law Firm on Unsplash',
  },
  {
    slug: 'how-to-break-lease-early',
    title: 'How to Break a Lease Early: Legal Options and Safer Steps',
    description: 'A renter-first guide to ending a lease early, with legal options, negotiation tips, and credit-safe steps.',
    content: '',
    author: 'Michael Chen',
    publishDate: '2025-01-22T10:00:00Z',
    lastModified: '2025-01-22T10:00:00Z',
    category: 'Legal Rights',
    tags: ['lease-termination', 'tenant-rights', 'legal', 'lease-break', 'early-termination'],
    readingTime: 16,
    image: '/images/legal-rights/how-to-break-lease-early/how-to-break-lease-early-hero.webp',
    imageAlt: 'Person reviewing lease contract documents for early termination options',
    imageCredit: 'Photo by Tingey Injury Law Firm on Unsplash',
  },
  {
    slug: 'first-apartment-checklist-guide-2025',
    title: 'First Apartment Checklist: A Practical Move-In Guide (2025)',
    description: 'A renter-first checklist covering landlord-provided items, room-by-room essentials, and a simple buying timeline.',
    content: '',
    author: 'Sarah Mitchell',
    publishDate: '2025-01-20T10:00:00Z',
    lastModified: '2025-01-20T10:00:00Z',
    category: 'Apartment Hunting',
    tags: ['first-apartment', 'apartment-checklist', 'budgeting', 'moving', 'first-time-renter'],
    readingTime: 18,
    image: '/images/apartment-hunting/first-apartment-checklist-guide-2025/first-apartment-checklist-guide-2025-hero.webp',
    imageAlt: 'Young person moving into first apartment with boxes and checklist',
    imageCredit: 'Photo by Ketut Subiyanto on Unsplash',
  },
  {
    slug: 'how-to-save-money-renting-2025',
    title: 'How to Save Money Renting in 2025: Practical Ways to Lower Costs',
    description: 'Practical, renter-first ways to lower rent, reduce fees, and cut monthly costs without risky shortcuts.',
    content: '', // Will be populated separately
    author: 'Sarah Mitchell',
    publishDate: '2025-01-15T10:00:00Z',
    lastModified: '2025-01-15T10:00:00Z',
    category: 'Money Saving',
    tags: ['rent-negotiation', 'budgeting', 'saving-money', 'rental-tips'],
    readingTime: 12,
    image: '/images/money-saving/how-to-save-money-renting-2025/how-to-save-money-renting-2025-hero.webp',
    imageAlt: 'Person calculating budget and savings on laptop',
    imageCredit: 'Photo by Kelly Sikkema on Unsplash',
  },
  {
    slug: 'tenant-rights-everyone-should-know',
    title: 'Tenant Rights Basics: Core Rights Every Renter Should Know',
    description: 'Understand core tenant rights, common lease issues, and how to handle repairs, deposits, and privacy concerns.',
    content: '',
    author: 'David Chen',
    publishDate: '2025-01-14T10:00:00Z',
    lastModified: '2025-02-02T10:00:00Z',
    category: 'Legal Rights',
    tags: ['tenant-rights', 'legal', 'lease-agreement', 'protection'],
    readingTime: 15,
    image: '/images/legal-rights/tenant-rights-everyone-should-know/tenant-rights-everyone-should-know-hero.webp',
    imageAlt: 'Legal documents and scales of justice',
    imageCredit: 'Photo by Tingey Injury Law Firm on Unsplash',
  },
  {
    slug: 'tenant-rights-by-state-overview',
    title: 'How Tenant Rights Differ by State: An Overview Guide',
    description: 'Learn how tenant rights vary by state, what rules change most often, and how to find local information.',
    content: '',
    author: 'RentingExplained Editorial Team',
    publishDate: '2025-02-02T10:00:00Z',
    lastModified: '2025-02-02T10:00:00Z',
    category: 'Legal Rights',
    tags: ['tenant-rights', 'state-laws', 'renter-protections', 'legal'],
    readingTime: 12,
    image: '/images/legal-rights/tenant-rights-by-state-overview/tenant-rights-by-state-overview-hero.webp',
    imageAlt: 'Person reviewing a lease and state law notes',
    imageCredit: 'Photo by Tingey Injury Law Firm on Unsplash',
  },
  {
    slug: 'security-deposits-and-evictions-overview',
    title: 'Understanding Security Deposits and Evictions: A General Education Guide',
    description: 'A plain-language overview of security deposits and eviction basics, including documentation tips.',
    content: '',
    author: 'RentingExplained Editorial Team',
    publishDate: '2025-02-01T10:00:00Z',
    lastModified: '2025-02-01T10:00:00Z',
    category: 'Legal Rights',
    tags: ['security-deposit', 'eviction', 'tenant-rights', 'legal'],
    readingTime: 11,
    image: '/images/legal-rights/security-deposits-and-evictions-overview/security-deposits-and-evictions-overview-hero.webp',
    imageAlt: 'Lease paperwork and keys on a desk',
    imageCredit: 'Photo by Tingey Injury Law Firm on Unsplash',
  },
  {
    slug: 'hidden-rental-fees-explained',
    title: 'Hidden Rental Fees Explained: What Renters Pay Beyond Base Rent',
    description: 'A clear guide to move-in fees, monthly add-ons, and how to spot and negotiate surprise charges.',
    content: '',
    author: 'Jessica Torres',
    publishDate: '2025-01-13T10:00:00Z',
    lastModified: '2025-01-13T10:00:00Z',
    category: 'Costs',
    tags: ['rental-fees', 'hidden-costs', 'budgeting', 'transparency'],
    readingTime: 10,
    image: '/images/costs/hidden-rental-fees-explained/hidden-rental-fees-explained-hero.webp',
    imageAlt: 'Calculator and financial documents showing fees',
    imageCredit: 'Photo by Towfiqu barbhuiya on Unsplash',
  },
  {
    slug: 'best-apps-and-tools-for-renters',
    title: 'Best Apps and Tools for Renters in 2025: Complete Comparison Guide',
    description: 'Compare the top rental apps and digital tools that make apartment hunting, rent payment, and tenant communication easier than ever.',
    content: '',
    author: 'Michael Rodriguez',
    publishDate: '2025-01-12T10:00:00Z',
    lastModified: '2025-01-12T10:00:00Z',
    category: 'Technology',
    tags: ['rental-apps', 'technology', 'tools', 'apartment-hunting'],
    readingTime: 11,
    image: '/images/technology/best-apps-and-tools-for-renters/best-apps-and-tools-for-renters-hero.webp',
    imageAlt: 'Smartphone showing rental apps and tools',
    imageCredit: 'Photo by Firmbee.com on Unsplash',
  },
  {
    slug: 'renting-vs-buying-2025',
    title: 'Renting vs Buying in 2025: A Practical Decision Guide',
    description: 'Compare renting and buying using real-life trade-offs like time horizon, total monthly cost, and flexibility.',
    content: '',
    author: 'Emily Watson',
    publishDate: '2025-01-11T10:00:00Z',
    lastModified: '2025-01-11T10:00:00Z',
    category: 'Financial Planning',
    tags: ['renting-vs-buying', 'real-estate', 'investment', 'financial-planning'],
    readingTime: 13,
    image: '/images/financial-planning/renting-vs-buying-2025/renting-vs-buying-2025-hero.webp',
    imageAlt: 'Modern house with for sale sign',
    imageCredit: 'Photo by Breno Assis on Unsplash',
  },
  {
    slug: 'lease-renewal-vs-moving-out',
    title: 'Lease Renewal vs. Moving Out: How to Make the Right Call',
    description: 'Should you renew your lease or move out? Compare the real costs of staying vs. moving, learn how to negotiate your renewal, and make the right call.',
    content: '',
    author: 'RentingExplained Editorial Team',
    publishDate: '2026-03-15T10:00:00Z',
    lastModified: '2026-03-15T10:00:00Z',
    category: 'Legal Rights',
    tags: ['lease-renewal', 'moving-out', 'tenant-rights', 'lease-negotiation', 'renter-decisions'],
    readingTime: 10,
    image: '/images/legal-rights/lease-renewal-vs-moving-out/lease-renewal-vs-moving-out-hero.webp',
    imageAlt: 'Renter reviewing lease renewal documents at kitchen table in a modern apartment',
    imageCredit: 'Photo by Unsplash',
  },
  {
    slug: 'apartment-lease-agreement-explained',
    title: 'Apartment Lease Agreement Explained: Key Clauses Every Renter Should Know',
    description: 'Understand every section of your apartment lease before signing. This plain-English guide explains key clauses, red flags, and what to negotiate.',
    content: '',
    author: 'RentingExplained Editorial Team',
    publishDate: '2026-03-15T10:00:00Z',
    lastModified: '2026-03-15T10:00:00Z',
    category: 'Legal Rights',
    tags: ['lease-agreement', 'tenant-rights', 'signing-lease', 'apartment-hunting', 'legal'],
    readingTime: 9,
    image: '/images/legal-rights/apartment-lease-agreement-explained/apartment-lease-agreement-explained-hero.webp',
    imageAlt: 'Person carefully reading a lease agreement document at a desk',
    imageCredit: 'Photo by Scott Graham on Unsplash',
  },
  {
    slug: 'landlord-entry-notice-requirements',
    title: 'Landlord Notice to Enter: How Much Notice Is Required? (2026)',
    description: 'Learn how much notice your landlord must give before entering your apartment, when emergency entry is allowed, and what to do if they violate your rights.',
    content: '',
    author: 'RentingExplained Editorial Team',
    publishDate: '2026-03-15T10:00:00Z',
    lastModified: '2026-03-15T10:00:00Z',
    category: 'Legal Rights',
    tags: ['tenant-rights', 'landlord-entry', 'notice-to-enter', 'legal', 'lease-agreement'],
    readingTime: 10,
    image: '/images/legal-rights/landlord-entry-notice-requirements/landlord-entry-notice-hero.webp',
    imageAlt: 'Landlord knocking on apartment door with clipboard',
    imageCredit: 'Photo by Unsplash',
  },
];

export function getArticleBySlug(slug: string): Article | undefined {
  return articles.find((article) => article.slug === slug);
}

export function getAllArticles(): Article[] {
  return articles.sort((a, b) => 
    new Date(b.publishDate).getTime() - new Date(a.publishDate).getTime()
  );
}

export function getArticlesByCategory(category: string): Article[] {
  return articles.filter((article) => article.category === category);
}

export function getArticlesByTag(tag: string): Article[] {
  return articles.filter((article) => article.tags.includes(tag));
}

export function getRelatedArticles(currentSlug: string, limit: number = 3): Article[] {
  const currentArticle = getArticleBySlug(currentSlug);
  if (!currentArticle) return [];

  // Find articles with matching tags
  const related = articles
    .filter((article) => 
      article.slug !== currentSlug &&
      article.tags.some((tag) => currentArticle.tags.includes(tag))
    )
    .sort((a, b) => {
      const aMatchCount = a.tags.filter((tag) => currentArticle.tags.includes(tag)).length;
      const bMatchCount = b.tags.filter((tag) => currentArticle.tags.includes(tag)).length;
      return bMatchCount - aMatchCount;
    })
    .slice(0, limit);

  return related;
}
